# Generated by Django 5.0.6 on 2025-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guests',
            name='email',
            field=models.CharField(default=' ', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guests',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
