# Generated by Django 5.0.6 on 2025-09-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fileupload_file_guests_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadguest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileuploadguest',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guests')),
            ],
            options={
                'db_table': 'event_guest',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.eventguest')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
    ]
